repos:
  ##############################################################################
  #  General checks
  ##############################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: forbid-new-submodules
      - id: end-of-file-fixer
        types_or: [rust, cython, python, markdown]
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        description: Checks for common misspellings.
        types_or: [python, cython, rst, markdown]
        args: ["-L", "ACN,crate,ot,socio-economic,zar"]

  ##############################################################################
  #  Rust formatting and linting
  ##############################################################################
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        description: Format files with cargo fmt.
        entry: cargo fmt
        language: system
        args: ["--all", "--", "--check"]
        files: '\.(rs|toml)$'
        types: [file]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Run the Clippy linter on the package.
        entry: cargo clippy
        language: system
        args: ["--benches", "--no-default-features", "--", "-D", "warnings"]
        files: '\.(rs|toml)$'
        types: [file]
        pass_filenames: false

      - id: cargo-doc
        name: cargo doc
        description: Check documentation builds without errors or warnings.
        entry: bash -c 'RUSTDOCFLAGS="--cfg docsrs -D warnings" cargo doc --no-deps --workspace --quiet'
        language: system
        files: '\.(rs|toml)$'
        types: [file]
        pass_filenames: false

  ##############################################################################
  #  Python/Cython formatting and linting
  ##############################################################################
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.1 # uv version
    hooks:
      - id: uv-lock
